name: build

on:
  push:
    branches: [ "main" ]


jobs:
  build-backend:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./backend
    
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
        
    - run: npm ci
    - run: npm run build --if-present
    #- run: sudo pm2 restart backend


  build-frontend:
    needs: build-backend
    runs-on: self-hosted 
    #change directory to frontend
    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - run: npm ci

  docker-compose:
    runs-on: self-hosted
    needs: build-frontend
  
    steps:
    - run: docker-compose up