name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]




jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: start ec2 instance 
      run: |
          aws ec2 start-instances --instance-ids ${{secrets.AWS_EC2_INSTANCE_ID }}
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    - name: Go to armoire folder
      run: cd armoire

    - name: Run Docker-Compose
      run: |
        docker-compose up
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
